/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/login/index" |
       "/pages/login/login2" |
       "/pages/login/phoneLogin" |
       "/pages/login/sfzLogin" |
       "/pages/mine/index" |
       "/pages/serve/index" |
       "/pages/shop/index" |
       "/pages/login/compoents/loginOuther" |
       "/pages-sub/serveMain/OcrCamera" |
       "/pages-sub/serveMain/cardApplyFromType" |
       "/pages-sub/serveMain/cardApplyType" |
       "/pages-sub/serveMain/cardFromType" |
       "/pages-sub/serveMain/cardMessType" |
       "/pages-sub/serveMassage/businessOutlets/index" |
       "/pages-sub/serveMassage/messageList/index" |
       "/pages-sub/serveMassage/newsManager/index" |
       "/pages-sub/serveMassage/serchFor/index" |
       "/pages-sub/serveMassage/workGuide/index" |
       "/pages-sub/webView/index" |
       "/pages-sub/system/sysconfig/index" |
       "/pages-sub/system/sysconfig/setting" |
       "/pages-sub/userManager/SocialSecurityCard/barcode" |
       "/pages-sub/userManager/SocialSecurityCard/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/serve/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
